name: Daily Score Backfill

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  run-backfill:
    runs-on: ubuntu-latest
    steps:
      - name: Hit /backfill-actuals to update scores
        run: |
          curl -X POST "$API_URL/backfill-actuals" \
            -H "x-api-key: $API_KEY"
        env:
          API_URL: ${{ secrets.API_URL }}
          API_KEY: ${{ secrets.API_KEY }}
