name: Wake Fly.io VM

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  wake:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Fly.io CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          export PATH="$HOME/.fly/bin:$PATH"

      - name: Authenticate with Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: fly auth token $FLY_API_TOKEN

      - name: Scale up to 1 machine
        run: fly scale count 1 --app your-app-name
