name: Sleep Fly.io VM

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  sleep:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Fly.io CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          export PATH="$HOME/.fly/bin:$PATH"

      - name: Authenticate with Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: fly auth token $FLY_API_TOKEN

      - name: Scale down to 0 machines
        run: fly scale count 0 --app backend-dry-butterfly-4692
