name: Wake Fly.io VM

on:
  schedule:
    - cron: '0 7 * * *' # 7 AM UTC
  workflow_dispatch:

jobs:
  sleep:
    runs-on: ubuntu-latest

    steps:
      - name: Install Fly.io CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - name: Scale up to 1 machine
        run: |
          export FLY_API_TOKEN=${{ secrets.FLY_API_TOKEN }}
          fly scale count 1 --app backend-dry-butterfly-4692
