name: Sleep Fly.io VM

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  sleep:
    runs-on: ubuntu-latest

    steps:
      - name: Install Fly.io CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - name: Scale down to 0 machines
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: fly scale count 0 --app backend-dry-butterfly-4692
